version: '3.1'

services:

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: baseballdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432
    volumes:
      - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data/csv:/csv
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: